### ISSUE TITLE
SunDawning: mi.com-去除推荐、微信指引、继续了解

### ISSUE THREAD

**Issue by SunDawning** [SunDawning/Stylish#28]
#### Screenshot

![](https://userstyles.org/style_screenshots/139614_after.jpeg)

#### Help

- Download: https://userstyles.org/styles/139614
- Feedback: https://github.com/SunDawning/Stylish/issues/28

#### Feature

- 精简部分内容：去除推荐、微信指引、继续了解等等诱导浏览的信息

#### Author

- Contact Me : SunDawning
- Email      : dpmeichen@gmail.com
- Copyright  : Copyright 2017 SunDawning. All Rights Reserved.

#### Version

- <2017-08-29 Tue 19:10:42> 修复 首页加载变慢的问题，使用新的元素隐藏方法
- <2017-07-14 Fri 09:03:18> 优化 调整评论页面内容的宽度，生效于 https 网址
- <2017-05-31 Wed 09:42:22> 新增 精简商品详情页面的重复导航、微信公众号等信息
- <2017-05-31 Wed 09:32:33> 修复 删除主页新出现的内容，调整高度来隐藏全屏下出现的滑动栏
- 修复 主页底栏异常 <2017-03-04 Sat 11:37:39>
- 新增 SunDawn: mi.com 自用 <2017-03-02 Thu 16:39:39>

**Comment by SunDawning** [comment]
隐藏元素的方法

```CSS
#content { display: none; }
```

或者

```CSS
#content { position: fixed; visibility: hidden; }
```
