### ISSUE TITLE
SunDawning-打印sundawning.github.io

### ISSUE THREAD

**Issue by SunDawning** [SunDawning/Stylish#31]
```css
@-moz-document domain("sundawning.github.io") {
@media print { #table-of-contents { position: inherit; border: none; }
	#table-of-contents #text-table-of-contents { display: inherit; }
	body { border: none; }
	#table-of-contents h2 { text-align: left; }
	pre.src { white-space: pre-line; max-height: inherit; }
	#postamble { display: block; position: inherit; }
	}
}
```
